version: '3.9'

services:
  web:  # GeoDjango-Service
    build:
      context: .
      dockerfile: Dockerfile  # Dockerfile für GeoDjango
    volumes:
      - .:/app:cached  # Nur für Entwicklung
    ports:
      - "8000:8000"  # GeoDjango läuft auf Port 8000
    environment:
      - DATABASE_URL=postgresql://admin:diHVnhwd9e3mX5A12tlVBNdN3SxO3kKw@dpg-ctvruvjtq21c73aiucv0-a.frankfurt-postgres.render.com/dbhempdata  # Verbindung zur Datenbank

  dash:  # Plotly Dash-Service
    build:
      context: .
      dockerfile: Dockerfile.dash  # Dockerfile speziell für Dash
    volumes:
      - ./dash_app:/app/dash_app:cached  # Nur Dash-App wird in den Container gemountet
    ports:
      - "8050:8050"  # Dash läuft auf Port 8050
    environment:
      - DATABASE_URL=postgresql://admin:diHVnhwd9e3mX5A12tlVBNdN3SxO3kKw@dpg-ctvruvjtq21c73aiucv0-a.frankfurt-postgres.render.com/dbhempdata  # Verbindung zur Datenbank

volumes:
  postgres_data:  # Benanntes Volume für Datenbankdaten
