# Generated by Django 5.1.2 on 2024-11-04 17:01

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('size', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Feld',
                'verbose_name_plural': 'Felder',
            },
        ),
        migrations.CreateModel(
            name='SurveyCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorien',
            },
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='hempdata.field')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='hempdata.surveycategory')),
            ],
            options={
                'verbose_name': 'Schlag',
                'verbose_name_plural': 'Schläge',
            },
        ),
        migrations.CreateModel(
            name='PreparationData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('crop_type', models.CharField(max_length=100)),
                ('seeding_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fertilization_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('soil_preparation', models.CharField(max_length=100)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparation_data', to='hempdata.plot')),
            ],
            options={
                'verbose_name': 'Preparation Data',
                'verbose_name_plural': 'Preparation Data',
            },
        ),
    ]
