# Generated by Django 5.1.2 on 2024-11-05 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hempdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preparationdata',
            options={'verbose_name': 'Feldvorbereitung', 'verbose_name_plural': 'Feldvorbereitungen'},
        ),
    ]
