# Generated by Django 5.1.3 on 2024-11-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hempdata', '0002_alter_preparationdata_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='size',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
