# Generated by Django 5.1.3 on 2024-11-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hempdata', '0003_alter_field_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plot',
            name='description',
        ),
        migrations.AlterField(
            model_name='plot',
            name='size',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
