# Generated by Django 5.1.3 on 2024-11-19 13:05

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hempdata', '0004_remove_plot_description_alter_plot_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Wettermessung',
                'verbose_name_plural': 'Wettermessungen',
            },
        ),
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name': 'Wetterstation',
                'verbose_name_plural': 'Wetterstation',
            },
        ),
        migrations.AlterField(
            model_name='field',
            name='size',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Größe (ha)'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='hempdata.surveycategory', verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='hempdata.field', verbose_name='In Feld'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Schlag ID'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='size',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Größe (ha)'),
        ),
        migrations.AlterField(
            model_name='preparationdata',
            name='crop_type',
            field=models.CharField(max_length=100, verbose_name='Kulturart'),
        ),
        migrations.AlterField(
            model_name='preparationdata',
            name='fertilization_amount',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Düngemenge (kg N/ha)'),
        ),
        migrations.AlterField(
            model_name='preparationdata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='preparationdata',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparation_data', to='hempdata.plot', verbose_name='Schlag'),
        ),
        migrations.AlterField(
            model_name='preparationdata',
            name='seeding_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Aussaatstärke (kg/ha)'),
        ),
        migrations.AlterField(
            model_name='preparationdata',
            name='soil_preparation',
            field=models.CharField(max_length=100, verbose_name='Bodenvorbereitung (qual. Beschreibung)'),
        ),
        migrations.CreateModel(
            name='PlantCharacteristicsBase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Wuchshöhe')),
                ('color', models.CharField(max_length=50, verbose_name='Blattfarbe')),
                ('growth_form', models.CharField(max_length=50, verbose_name='Wuchsform')),
                ('stem_diameter', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Stängeldurchmesser')),
                ('damage', models.TextField(verbose_name='Schaden (Wild, Hadel, etc.)')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_characteristics_base', to='hempdata.plot', verbose_name='Schlag')),
            ],
            options={
                'verbose_name': 'Pflanzenmerkmal - unten',
                'verbose_name_plural': 'Pflanzenmerkmale - unten',
            },
        ),
        migrations.CreateModel(
            name='PlantCharacteristicsTop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_characteristics_top', to='hempdata.plot', verbose_name='Schlag')),
            ],
            options={
                'verbose_name': 'Pflanzenmerkmale - oben',
                'verbose_name_plural': 'Pflanzenmerkmale - oben',
            },
        ),
        migrations.CreateModel(
            name='SoilData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_data', to='hempdata.plot', verbose_name='Schlag')),
            ],
            options={
                'verbose_name': 'Bodenanalyse',
                'verbose_name_plural': 'Bodenanalysen',
            },
        ),
    ]
