# Generated by Django 5.1.3 on 2024-12-03 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hempdata', '0005_weatherdata_weatherstation_alter_field_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plot',
            name='field',
        ),
        migrations.RemoveField(
            model_name='plantcharacteristicsbase',
            name='plot',
        ),
        migrations.RemoveField(
            model_name='plantcharacteristicstop',
            name='plot',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='category',
        ),
        migrations.RemoveField(
            model_name='soildata',
            name='plot',
        ),
        migrations.RemoveField(
            model_name='preparationdata',
            name='plot',
        ),
        migrations.DeleteModel(
            name='WeatherData',
        ),
        migrations.DeleteModel(
            name='WeatherStation',
        ),
        migrations.DeleteModel(
            name='Field',
        ),
        migrations.DeleteModel(
            name='PlantCharacteristicsBase',
        ),
        migrations.DeleteModel(
            name='PlantCharacteristicsTop',
        ),
        migrations.DeleteModel(
            name='SurveyCategory',
        ),
        migrations.DeleteModel(
            name='SoilData',
        ),
        migrations.DeleteModel(
            name='Plot',
        ),
        migrations.DeleteModel(
            name='PreparationData',
        ),
    ]
