# Generated by Django 5.1.3 on 2024-12-03 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hempdata', '0007_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conditioning',
            name='plot',
        ),
        migrations.RemoveField(
            model_name='fertilization',
            name='plot',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='field',
        ),
        migrations.RemoveField(
            model_name='harvest',
            name='plot',
        ),
        migrations.RemoveField(
            model_name='historicaldata',
            name='plot',
        ),
        migrations.RemoveField(
            model_name='weedcontrolmechanic',
            name='plot',
        ),
        migrations.RemoveField(
            model_name='topcut',
            name='plot',
        ),
        migrations.RemoveField(
            model_name='soilpreparation',
            name='plot',
        ),
        migrations.RemoveField(
            model_name='weedcontrolchemical',
            name='plot',
        ),
        migrations.RemoveField(
            model_name='seeding',
            name='plot',
        ),
        migrations.DeleteModel(
            name='Bailing',
        ),
        migrations.DeleteModel(
            name='Conditioning',
        ),
        migrations.DeleteModel(
            name='Fertilization',
        ),
        migrations.DeleteModel(
            name='Field',
        ),
        migrations.DeleteModel(
            name='Harvest',
        ),
        migrations.DeleteModel(
            name='HistoricalData',
        ),
        migrations.DeleteModel(
            name='WeedControlMechanic',
        ),
        migrations.DeleteModel(
            name='TopCut',
        ),
        migrations.DeleteModel(
            name='SoilPreparation',
        ),
        migrations.DeleteModel(
            name='WeedControlChemical',
        ),
        migrations.DeleteModel(
            name='Plot',
        ),
        migrations.DeleteModel(
            name='Seeding',
        ),
    ]
