# Generated by Django 5.1.3 on 2024-12-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hempdata', '0009_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bailing',
            options={'verbose_name': 'Prozessdaten 9 - Ballen', 'verbose_name_plural': 'Prozessdaten 9 - Ballen'},
        ),
        migrations.AlterModelOptions(
            name='conditioning',
            options={'verbose_name': 'Prozessdaten 8 - Konditionierung', 'verbose_name_plural': 'Prozessdaten 8 - Konditionierung'},
        ),
        migrations.AlterModelOptions(
            name='fertilization',
            options={'verbose_name': 'Prozessdaten 2 - Düngung', 'verbose_name_plural': 'Prozessdaten 2 - Düngung'},
        ),
        migrations.AlterModelOptions(
            name='field',
            options={'verbose_name': 'Aufteilung - Feld', 'verbose_name_plural': 'Aufteilung - Felder'},
        ),
        migrations.AlterModelOptions(
            name='harvest',
            options={'verbose_name': 'Prozessdaten 7 - Ernte', 'verbose_name_plural': 'Prozessdaten 7 - Ernte'},
        ),
        migrations.AlterModelOptions(
            name='historicaldata',
            options={'verbose_name': 'Historische Daten', 'verbose_name_plural': 'Historische Daten'},
        ),
        migrations.AlterModelOptions(
            name='plot',
            options={'verbose_name': 'Aufteilung - Schlag', 'verbose_name_plural': 'Aufteilung - Schläge'},
        ),
        migrations.AlterModelOptions(
            name='seeding',
            options={'verbose_name': 'Prozessdaten 3 - Aussaat', 'verbose_name_plural': 'Prozessdaten 3 - Aussaat'},
        ),
        migrations.AlterModelOptions(
            name='soilpreparation',
            options={'verbose_name': 'Prozessdaten 1 - Bodenvorbereitung', 'verbose_name_plural': 'Prozessdaten 1 - Bodenvorbereitungen'},
        ),
        migrations.AlterModelOptions(
            name='topcut',
            options={'verbose_name': 'Prozessdaten 4 - Kopfschnitt', 'verbose_name_plural': 'Prozessdaten 4 - Kopfschnitt'},
        ),
        migrations.AlterModelOptions(
            name='weedcontrolchemical',
            options={'verbose_name': 'Prozessdaten 6 - Unkrautbekämpfung - Chemisch', 'verbose_name_plural': 'Prozessdaten 6 - Unkrautbekämpfung - Chemisch'},
        ),
        migrations.AlterModelOptions(
            name='weedcontrolmechanic',
            options={'verbose_name': 'Prozessdaten 5 - Unkrautbekämpfung - Mechanisch', 'verbose_name_plural': 'Prozessdaten 5 - Unkrautbekämpfung - Mechanisch'},
        ),
        migrations.AddField(
            model_name='plot',
            name='name',
            field=models.CharField(default='name', max_length=255),
            preserve_default=False,
        ),
    ]
