# Generated by Django 5.1.3 on 2024-12-04 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hempdata', '0010_alter_bailing_options_alter_conditioning_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilization',
            name='amount',
            field=models.IntegerField(verbose_name='Menge (kg/ha)'),
        ),
        migrations.AlterField(
            model_name='fertilization',
            name='completed',
            field=models.BooleanField(default=True, verbose_name='Düngung erfolgt'),
        ),
        migrations.AlterField(
            model_name='fertilization',
            name='created_at',
            field=models.DateTimeField(verbose_name='Zeitpunkt der Düngung'),
        ),
        migrations.AlterField(
            model_name='fertilization',
            name='fertilizer',
            field=models.CharField(choices=[('type1', 'Type 1'), ('type2', 'Type 2'), ('type3', 'Type 3')], max_length=50, verbose_name='Dünger'),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Eintrag vom'),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_data', to='hempdata.plot', verbose_name='Schlag'),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='previous_crop1',
            field=models.CharField(max_length=255, verbose_name='Vorfrucht 1'),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='previous_crop2',
            field=models.CharField(max_length=255, verbose_name='Vorfrucht 2'),
        ),
        migrations.AlterField(
            model_name='soilpreparation',
            name='completed',
            field=models.BooleanField(default=True, verbose_name='Durchgeführt'),
        ),
        migrations.AlterField(
            model_name='soilpreparation',
            name='intensity',
            field=models.CharField(choices=[('flach', 'Flach'), ('mittel', 'Mittel'), ('tief', 'Tief')], max_length=10, verbose_name='Intensität'),
        ),
        migrations.AlterField(
            model_name='soilpreparation',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_preparations', to='hempdata.plot', verbose_name='Schlag'),
        ),
        migrations.AlterField(
            model_name='soilpreparation',
            name='type',
            field=models.CharField(max_length=255, verbose_name='Art der Durchführung'),
        ),
    ]
