# Generated by Django 5.1.3 on 2024-12-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hempdata', '0011_alter_fertilization_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilization',
            name='created_at',
            field=models.DateField(verbose_name='Zeitpunkt der Düngung'),
        ),
    ]
