# Generated by Django 5.1.3 on 2024-12-04 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hempdata', '0012_alter_fertilization_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilization',
            name='created_at',
            field=models.DateField(default=datetime.date(2024, 12, 4), verbose_name='Zeitpunkt der Düngung'),
        ),
    ]
