# Generated by Django 5.1.3 on 2024-12-04 10:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hempdata', '0013_alter_fertilization_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilization',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Zeitpunkt der Düngung'),
        ),
    ]
