# Generated by Django 5.1.3 on 2024-12-04 13:01

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hempdata', '0014_alter_fertilization_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Verlaufsanalytik - Wettermessung',
                'verbose_name_plural': 'Verlaufsanalytik - Wettermessungen',
            },
        ),
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name': 'Standort - Wetterstation',
                'verbose_name_plural': 'Standort - Wetterstationen',
            },
        ),
        migrations.AlterModelOptions(
            name='field',
            options={'verbose_name': 'Standort - Feld', 'verbose_name_plural': 'Standort - Felder'},
        ),
        migrations.AlterModelOptions(
            name='plot',
            options={'verbose_name': 'Standort - Schlag', 'verbose_name_plural': 'Standort - Schläge'},
        ),
        migrations.AlterModelOptions(
            name='topcut',
            options={'verbose_name': 'Bestandspflege - Kopfschnitt', 'verbose_name_plural': 'Bestandspflege - Kopfschnitt'},
        ),
        migrations.AlterModelOptions(
            name='weedcontrolchemical',
            options={'verbose_name': 'Bestandspflege - Unkrautbekämpfung - Chemisch', 'verbose_name_plural': 'Bestandspflege - Unkrautbekämpfung - Chemisch'},
        ),
        migrations.AlterModelOptions(
            name='weedcontrolmechanic',
            options={'verbose_name': 'Bestandspflege - Unkrautbekämpfung - Mechanisch', 'verbose_name_plural': 'Bestandspflege - Unkrautbekämpfung - Mechanisch'},
        ),
        migrations.CreateModel(
            name='PlantCharacteristicsBase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_characteristics_base', to='hempdata.plot', verbose_name='Schlag')),
            ],
            options={
                'verbose_name': 'Verlaufsanalytik - Pflanzenmerkmal - Analog',
                'verbose_name_plural': 'Verlaufsanalytik - Pflanzenmerkmale - Analog',
            },
        ),
        migrations.CreateModel(
            name='PlantCharacteristicsTop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_characteristics_top', to='hempdata.plot', verbose_name='Schlag')),
            ],
            options={
                'verbose_name': 'Verlaufsanalytik - Pflanzenmerkmale - Drohne',
                'verbose_name_plural': 'Verlaufsanalytik - Pflanzenmerkmale - Drohne',
            },
        ),
        migrations.CreateModel(
            name='SoilData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_data', to='hempdata.plot', verbose_name='Schlag')),
            ],
            options={
                'verbose_name': 'Verlaufsanalytik - Bodenanalyse',
                'verbose_name_plural': 'Verlaufsanalytik - Bodenanalysen',
            },
        ),
    ]
