# Generated by Django 5.1.3 on 2024-12-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hempdata', '0015_weatherdata_weatherstation_alter_field_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='historicaldata',
            constraint=models.UniqueConstraint(fields=('plot',), name='unique_plot_historical_data'),
        ),
    ]
