# Generated by Django 5.1.3 on 2024-12-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hempdata', '0017_alter_bailing_created_at_alter_bailing_plot_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantcharacteristicsbase',
            options={'verbose_name': 'Verlaufsanalytik - Pflanzenmerkmal - Manuell', 'verbose_name_plural': 'Verlaufsanalytik - Pflanzenmerkmale - Manuell'},
        ),
        migrations.AddField(
            model_name='plantcharacteristicsbase',
            name='growth_form',
            field=models.CharField(choices=[(10, '10%'), (20, '20%'), (30, '30%'), (40, '40%'), (50, '50%'), (60, '60%'), (70, '70%'), (80, '80%'), (90, '90%'), (100, '100%')], default=10, max_length=20, verbose_name='Wuchsform (%-Anteil gerade)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantcharacteristicsbase',
            name='plant_density',
            field=models.IntegerField(default=10, verbose_name='Pflanzendichte (Pflanzen pro qm)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantcharacteristicsbase',
            name='shoots_number',
            field=models.CharField(choices=[(10, '10%'), (20, '20%'), (30, '30%'), (40, '40%'), (50, '50%'), (60, '60%'), (70, '70%'), (80, '80%'), (90, '90%'), (100, '100%')], default=10, max_length=20, verbose_name='Topcut-Triebzahl (%-Anteil Doppeltriebe)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantcharacteristicsbase',
            name='stem_thickness_one',
            field=models.IntegerField(default=0, verbose_name='Stängeldicke - Messstelle 1 - (x cm von Boden)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantcharacteristicsbase',
            name='stem_thickness_two',
            field=models.IntegerField(default=0, verbose_name='Stängeldicke - Messstelle 2 - (x cm von Boden)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plantcharacteristicsbase',
            name='topcut',
            field=models.BooleanField(default=0, verbose_name='Topcut'),
            preserve_default=False,
        ),
    ]
