# Generated by Django 5.1.3 on 2024-12-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hempdata', '0019_alter_plantcharacteristicsbase_growth_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantcharacteristicsbase',
            name='growth_form',
            field=models.IntegerField(choices=[(10, '10%'), (20, '20%'), (30, '30%'), (40, '40%'), (50, '50%'), (60, '60%'), (70, '70%'), (80, '80%'), (90, '90%'), (100, '100%')], max_length=20, verbose_name='Wuchsform (%-Anteil gerade)'),
        ),
        migrations.AlterField(
            model_name='plantcharacteristicsbase',
            name='shoots_number',
            field=models.IntegerField(choices=[(10, '10%'), (20, '20%'), (30, '30%'), (40, '40%'), (50, '50%'), (60, '60%'), (70, '70%'), (80, '80%'), (90, '90%'), (100, '100%')], max_length=20, verbose_name='Topcut-Triebzahl (%-Anteil Doppeltriebe)'),
        ),
    ]
