# Generated by Django 5.1.3 on 2024-12-10 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hempdata', '0022_alter_plantcharacteristicsbase_growth_form_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantcharacteristicsbase',
            options={'verbose_name': 'Verlaufsanalytik - Manuell- Pflanzenmerkmale', 'verbose_name_plural': 'Verlaufsanalytik - Manuell- Pflanzenmerkmale'},
        ),
        migrations.CreateModel(
            name='SoilSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_value', models.FloatField(help_text='pH-Wert des Bodens', verbose_name='pH-Wert')),
                ('cn_ratio', models.FloatField(help_text='Verhältnis von Kohlenstoff zu Stickstoff', verbose_name='C/N Verhältnis')),
                ('nitrogen_content', models.FloatField(help_text='Stickstoffgehalt des Bodens in g/kg', verbose_name='Stickstoffgehalt (g/kg)')),
                ('moisture_content', models.FloatField(help_text='Feuchtigkeit des Bodens in %', verbose_name='Bodenfeuchtigkeit (%)')),
                ('soil_texture', models.CharField(help_text='Bodenart (z.B. sandig, lehmig, tonig)', max_length=100, verbose_name='Bodenart')),
                ('phosphorus_availability', models.FloatField(help_text='Verfügbarkeit von Phosphor im Boden', verbose_name='Phosphorverfügbarkeit (mg/kg)')),
                ('salt_content', models.FloatField(help_text='Salzgehalt des Bodens in g/kg', verbose_name='Salzgehalt (g/kg)')),
                ('soil_compaction', models.FloatField(help_text='Bodenverdichtung in kg/cm²', verbose_name='Bodenverdichtung (kg/cm²)')),
                ('sampling_date', models.DateField(help_text='Datum der Bodenprobenahme', verbose_name='Probenahmedatum')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_samples', to='hempdata.plot', verbose_name='Schlag')),
            ],
            options={
                'verbose_name': 'Verlaufsanalytik - Manuell- Bodenproben',
                'verbose_name_plural': 'Verlaufsanalytik - Manuell- Bodenproben',
            },
        ),
        migrations.DeleteModel(
            name='SoilData',
        ),
    ]
