# Generated by Django 5.1.3 on 2024-12-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hempdata', '0023_alter_plantcharacteristicsbase_options_soilsample_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soilsample',
            name='cn_ratio',
            field=models.FloatField(blank=True, help_text='Verhältnis von Kohlenstoff zu Stickstoff', null=True, verbose_name='C/N Verhältnis'),
        ),
        migrations.AlterField(
            model_name='soilsample',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='soilsample',
            name='moisture_content',
            field=models.FloatField(blank=True, help_text='Feuchtigkeit des Bodens in %', null=True, verbose_name='Bodenfeuchtigkeit (%)'),
        ),
        migrations.AlterField(
            model_name='soilsample',
            name='nitrogen_content',
            field=models.FloatField(blank=True, help_text='Stickstoffgehalt des Bodens in g/kg', null=True, verbose_name='Stickstoffgehalt (g/kg)'),
        ),
        migrations.AlterField(
            model_name='soilsample',
            name='ph_value',
            field=models.FloatField(blank=True, help_text='pH-Wert des Bodens', null=True, verbose_name='pH-Wert'),
        ),
        migrations.AlterField(
            model_name='soilsample',
            name='phosphorus_availability',
            field=models.FloatField(blank=True, help_text='Verfügbarkeit von Phosphor im Boden', null=True, verbose_name='Phosphorverfügbarkeit (mg/kg)'),
        ),
        migrations.AlterField(
            model_name='soilsample',
            name='salt_content',
            field=models.FloatField(blank=True, help_text='Salzgehalt des Bodens in g/kg', null=True, verbose_name='Salzgehalt (g/kg)'),
        ),
        migrations.AlterField(
            model_name='soilsample',
            name='soil_compaction',
            field=models.FloatField(blank=True, help_text='Bodenverdichtung in kg/cm²', null=True, verbose_name='Bodenverdichtung (kg/cm²)'),
        ),
        migrations.AlterField(
            model_name='soilsample',
            name='soil_texture',
            field=models.CharField(blank=True, help_text='Bodenart (z.B. sandig, lehmig, tonig)', max_length=100, null=True, verbose_name='Bodenart'),
        ),
    ]
