# Generated by Django 5.1.3 on 2024-12-11 11:22

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hempdata', '0024_alter_soilsample_cn_ratio_alter_soilsample_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilization',
            name='amount',
            field=models.IntegerField(help_text='Die Düngermenge pro Hektar (kg/ha).', verbose_name='Menge (kg/ha)'),
        ),
        migrations.AlterField(
            model_name='fertilization',
            name='completed',
            field=models.BooleanField(default=True, help_text='Gibt an, ob die Düngung abgeschlossen wurde.', verbose_name='Düngung erfolgt'),
        ),
        migrations.AlterField(
            model_name='fertilization',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, help_text='Das Datum, an dem die Düngung durchgeführt wurde.', verbose_name='Zeitpunkt der Düngung'),
        ),
        migrations.AlterField(
            model_name='fertilization',
            name='fertilizer',
            field=models.CharField(choices=[('type1', 'Type 1'), ('type2', 'Type 2'), ('type3', 'Type 3')], help_text='Der verwendete Dünger (z. B. NPK, Kalk).', max_length=50, verbose_name='Dünger'),
        ),
        migrations.AlterField(
            model_name='fertilization',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Eindeutige ID der Düngung.', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fertilization',
            name='plot',
            field=models.ForeignKey(help_text='Das Feld (Plot), für das die Düngung durchgeführt wurde.', on_delete=django.db.models.deletion.CASCADE, related_name='fertilizations', to='hempdata.plot', verbose_name='Schlag'),
        ),
        migrations.AlterField(
            model_name='field',
            name='location',
            field=django.contrib.gis.db.models.fields.PolygonField(help_text='Polygongeometrie zur Darstellung der geographischen Lage des Feldes.', srid=4326, verbose_name='Geographische Lage'),
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(help_text='Der Name des Feldes, um es eindeutig zu identifizieren.', max_length=255, verbose_name='Name des Feldes'),
        ),
        migrations.AlterField(
            model_name='field',
            name='size',
            field=models.IntegerField(help_text='Die Größe des Feldes in Quadratmetern.', verbose_name='Größe des Feldes (m²)'),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='created_at',
            field=models.DateField(auto_now_add=True, help_text='Das Datum, an dem die historischen Daten erfasst wurden.', verbose_name='Erhebungszeitpunkt'),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Eindeutige ID der historischen Daten.', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='plot',
            field=models.ForeignKey(help_text='Das Feld (Plot), dem diese historischen Daten zugeordnet sind.', on_delete=django.db.models.deletion.CASCADE, related_name='historical_data', to='hempdata.plot', verbose_name='Schlag'),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='previous_crop1',
            field=models.CharField(help_text='Die erste Vorfrucht, die im Vorjahr auf diesem Schlag angebaut wurde.', max_length=255, verbose_name='Vorfrucht 1'),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='previous_crop2',
            field=models.CharField(help_text='Die zweite Vorfrucht, die vor zwei Jahren auf diesem Schlag angebaut wurde.', max_length=255, verbose_name='Vorfrucht 2'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='created_at',
            field=models.DateField(auto_now_add=True, help_text='Datum, an dem der Schlag erfasst wurde.', verbose_name='Erhebungszeitpunkt'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='field',
            field=models.ForeignKey(help_text='Das Feld, dem dieser Schlag zugeordnet ist.', on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='hempdata.field', verbose_name='Zugehöriges Feld'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='location',
            field=django.contrib.gis.db.models.fields.PolygonField(help_text='Polygongeometrie zur Darstellung der geographischen Lage des Schlags.', srid=4326, verbose_name='Geographische Lage'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='name',
            field=models.CharField(help_text='Der Name des Schlags, um ihn eindeutig zu identifizieren.', max_length=255, verbose_name='Name des Schlags'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='size',
            field=models.IntegerField(help_text='Die Größe des Schlags in Quadratmetern.', verbose_name='Größe des Schlags (m²)'),
        ),
        migrations.AlterField(
            model_name='seeding',
            name='created_at',
            field=models.DateField(auto_now_add=True, help_text='Das Datum, an dem die Aussaat erfasst wurde.', verbose_name='Erhebungszeitpunkt'),
        ),
        migrations.AlterField(
            model_name='seeding',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Eindeutige ID der Aussaat.', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='seeding',
            name='plot',
            field=models.ForeignKey(help_text='Das Feld (Plot), für das die Aussaat durchgeführt wurde.', on_delete=django.db.models.deletion.CASCADE, related_name='seedings', to='hempdata.plot', verbose_name='Schlag'),
        ),
        migrations.AlterField(
            model_name='seeding',
            name='seedbed_width',
            field=models.IntegerField(help_text='Die Breite des Saatbettes in Zentimetern.', verbose_name='Saatbettreite (cm)'),
        ),
        migrations.AlterField(
            model_name='seeding',
            name='seeding_rate',
            field=models.IntegerField(help_text='Die Menge an Saatgut, die pro Hektar ausgesät wurde (in kg/ha).', verbose_name='Ausaatstärke (kg/ha)'),
        ),
        migrations.AlterField(
            model_name='seeding',
            name='thousand_grain_weight',
            field=models.FloatField(default=12.5, help_text='Das Gewicht von tausend Körnern der ausgesäten Kultur (in Gramm).', verbose_name='Tausendkorngewicht (g)'),
        ),
        migrations.AlterField(
            model_name='seeding',
            name='variety',
            field=models.CharField(help_text='Die Kulturart (z.B. Weizen, Mais), die ausgesät wurde.', max_length=255, verbose_name='Kulturart'),
        ),
        migrations.AlterField(
            model_name='soilpreparation',
            name='completed',
            field=models.BooleanField(default=True, help_text='Gibt an, ob die Bodenvorbereitung abgeschlossen ist.', verbose_name='Durchgeführt'),
        ),
        migrations.AlterField(
            model_name='soilpreparation',
            name='created_at',
            field=models.DateField(auto_now_add=True, help_text='Das Datum, an dem die Bodenvorbereitung erfasst wurde.', verbose_name='Erhebungszeitpunkt'),
        ),
        migrations.AlterField(
            model_name='soilpreparation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Eindeutige ID der Bodenvorbereitung.', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='soilpreparation',
            name='intensity',
            field=models.CharField(choices=[('flach', 'Flach'), ('mittel', 'Mittel'), ('tief', 'Tief')], help_text='Die Intensität der Bodenvorbereitung (Flach, Mittel, Tief).', max_length=10, verbose_name='Intensität'),
        ),
        migrations.AlterField(
            model_name='soilpreparation',
            name='plot',
            field=models.ForeignKey(help_text='Das Feld (Plot), für das die Bodenvorbereitung durchgeführt wurde.', on_delete=django.db.models.deletion.CASCADE, related_name='soil_preparations', to='hempdata.plot', verbose_name='Schlag'),
        ),
        migrations.AlterField(
            model_name='soilpreparation',
            name='type',
            field=models.CharField(help_text='Die Art der durchgeführten Bodenvorbereitung (z. B. Pflügen, Eggen).', max_length=255, verbose_name='Art der Durchführung'),
        ),
        migrations.AlterField(
            model_name='soilsample',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_samples', to='hempdata.plot', verbose_name='Schlag *'),
        ),
        migrations.AlterField(
            model_name='soilsample',
            name='sampling_date',
            field=models.DateField(help_text='Datum der Bodenprobenahme', verbose_name='Probenahmedatum *'),
        ),
        migrations.AlterField(
            model_name='topcut',
            name='created_at',
            field=models.DateField(auto_now_add=True, help_text='Das Datum, an dem der Kopfschnitt erfasst wurde.', verbose_name='Erhebungszeitpunkt'),
        ),
        migrations.AlterField(
            model_name='topcut',
            name='cutting_height',
            field=models.IntegerField(help_text='Die Höhe, auf der der Kopfschnitt durchgeführt wurde (in cm).', verbose_name='Schnitthöhe'),
        ),
        migrations.AlterField(
            model_name='topcut',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Eindeutige ID des Kopfschnitts.', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='topcut',
            name='plot',
            field=models.ForeignKey(help_text='Das Feld (Plot), für das der Kopfschnitt durchgeführt wurde.', on_delete=django.db.models.deletion.CASCADE, related_name='topcuts', to='hempdata.plot', verbose_name='Schlag'),
        ),
        migrations.AlterField(
            model_name='weatherstation',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(help_text='Geographische Punktposition der Wetterstation, um den genauen Standort anzugeben.', srid=4326, verbose_name='Standort'),
        ),
        migrations.AlterField(
            model_name='weedcontrolmechanic',
            name='created_at',
            field=models.DateField(auto_now_add=True, help_text='Das Datum, an dem die mechanische Unkrautbekämpfung erfasst wurde.', verbose_name='Erhebungszeitpunkt'),
        ),
        migrations.AlterField(
            model_name='weedcontrolmechanic',
            name='emergence',
            field=models.CharField(choices=[('Nach dem Auflauf', 'Nach dem Auflauf'), ('Vor dem Auflauf', 'Vor dem Auflauf')], help_text='Gibt an, ob die Unkrautbekämpfung vor oder nach dem Auflaufen der Kultur durchgeführt wurde.', max_length=20, verbose_name='Nach/Vor dem Auflauf'),
        ),
        migrations.AlterField(
            model_name='weedcontrolmechanic',
            name='hacken',
            field=models.BooleanField(default=False, help_text='Gibt an, ob das Hacken als Unkrautbekämpfungsmethode angewendet wurde.', verbose_name='Hacken'),
        ),
        migrations.AlterField(
            model_name='weedcontrolmechanic',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Eindeutige ID der mechanischen Unkrautbekämpfung.', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='weedcontrolmechanic',
            name='plot',
            field=models.ForeignKey(help_text='Das Feld (Plot), für das die mechanische Unkrautbekämpfung durchgeführt wurde.', on_delete=django.db.models.deletion.CASCADE, related_name='mechanic_weed_controls', to='hempdata.plot', verbose_name='Schlag'),
        ),
        migrations.AlterField(
            model_name='weedcontrolmechanic',
            name='rollen',
            field=models.BooleanField(default=False, help_text='Gibt an, ob das Rollen als Unkrautbekämpfungsmethode verwendet wurde.', verbose_name='Rollen'),
        ),
        migrations.AlterField(
            model_name='weedcontrolmechanic',
            name='striegeln',
            field=models.BooleanField(default=False, help_text='Gibt an, ob das Striegeln zur Unkrautbekämpfung durchgeführt wurde.', verbose_name='Striegeln'),
        ),
    ]
