# Generated by Django 5.1.3 on 2024-12-11 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hempdata', '0025_alter_fertilization_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soilpreparation',
            name='plot',
            field=models.ForeignKey(help_text='Das Feld (Plot), für das die Bodenvorbereitung durchgeführt wurde.', on_delete=django.db.models.deletion.CASCADE, related_name='soil_preparation', to='hempdata.plot', verbose_name='Schlag'),
        ),
    ]
