# Generated by Django 5.1.3 on 2024-12-11 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hempdata', '0026_alter_soilpreparation_plot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvest',
            name='created_at',
            field=models.DateField(verbose_name='Erhebungszeitpunkt'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='procedure',
            field=models.CharField(choices=[('Wirr', 'Wirr'), ('Parallel', 'Parallel')], max_length=20, verbose_name='Ernte-Prozedur'),
        ),
        migrations.AlterField(
            model_name='soilpreparation',
            name='completed',
            field=models.BooleanField(default=True, verbose_name='Durchgeführt'),
        ),
        migrations.AlterField(
            model_name='soilpreparation',
            name='plot',
            field=models.ForeignKey(help_text='Der Schlag, für den die Bodenvorbereitung durchgeführt wurde.', on_delete=django.db.models.deletion.CASCADE, related_name='soil_preparation', to='hempdata.plot', verbose_name='Schlag'),
        ),
    ]
