# Generated by Django 5.1.3 on 2024-12-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hempdata', '0028_remove_weedcontrolmechanic_hacken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weedcontrolmechanic',
            name='procedure',
            field=models.CharField(choices=[('Hacken', 'Hacken'), ('Striegeln', 'Striegeln'), ('Rollen', 'Rollen')], default='Hacken', help_text='Gibt an, welche Art von Unkrautbekämpfung durchgeführt wurde.', max_length=20, verbose_name='Nach/Vor dem Auflauf'),
        ),
    ]
