# Generated by Django 5.1.3 on 2025-01-07 12:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hempdata', '0030_alter_weedcontrolmechanic_procedure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bailing',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bailings', to='hempdata.plot', verbose_name='Schlag *'),
        ),
        migrations.AlterField(
            model_name='conditioning',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, help_text='Das Datum, an dem die Konditionierung durchgeführt wurde.', verbose_name='Datum *'),
        ),
        migrations.AlterField(
            model_name='conditioning',
            name='plot',
            field=models.ForeignKey(help_text='Der Schlag, in dem die Konditionierungsmaßnahmen durchgeführt wurden.', on_delete=django.db.models.deletion.CASCADE, related_name='conditioning', to='hempdata.plot', verbose_name='Schlag *'),
        ),
        migrations.AlterField(
            model_name='fertilization',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, help_text='Das Datum, an dem die Düngung durchgeführt wurde.', verbose_name='Datum *'),
        ),
        migrations.AlterField(
            model_name='fertilization',
            name='plot',
            field=models.ForeignKey(help_text='Der Schlag, für den die Düngung durchgeführt wurde.', on_delete=django.db.models.deletion.CASCADE, related_name='fertilizations', to='hempdata.plot', verbose_name='Schlag *'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, help_text='Das Datum, an dem die Ernte durchgeführt wurde.', verbose_name='Datum *'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='plot',
            field=models.ForeignKey(help_text='Der Schlag, für den die Ernte vorgenommen wurde.', on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='hempdata.plot', verbose_name='Schlag *'),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='plot',
            field=models.ForeignKey(help_text='Das Feld (Plot), dem diese historischen Daten zugeordnet sind.', on_delete=django.db.models.deletion.CASCADE, related_name='historical_data', to='hempdata.plot', verbose_name='Schlag *'),
        ),
        migrations.AlterField(
            model_name='plantcharacteristicsbase',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_characteristics_base', to='hempdata.plot', verbose_name='Schlag *'),
        ),
        migrations.AlterField(
            model_name='plantcharacteristicstop',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_characteristics_top', to='hempdata.plot', verbose_name='Schlag *'),
        ),
        migrations.AlterField(
            model_name='seeding',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, help_text='Das Datum, an dem die Aussaat vorgenommen wurde.', verbose_name='Datum *'),
        ),
        migrations.AlterField(
            model_name='seeding',
            name='plot',
            field=models.ForeignKey(help_text='Der Schlag, für den die Aussaat durchgeführt wurde.', on_delete=django.db.models.deletion.CASCADE, related_name='seedings', to='hempdata.plot', verbose_name='Schlag *'),
        ),
        migrations.AlterField(
            model_name='soilpreparation',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, help_text='Das Datum, an dem die Düngung durchgeführt wurde.', verbose_name='Datum *'),
        ),
        migrations.AlterField(
            model_name='soilpreparation',
            name='plot',
            field=models.ForeignKey(help_text='Der Schlag, für den die Bodenvorbereitung durchgeführt wurde.', on_delete=django.db.models.deletion.CASCADE, related_name='soil_preparation', to='hempdata.plot', verbose_name='Schlag *'),
        ),
        migrations.AlterField(
            model_name='topcut',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, help_text='Das Datum, an dem der Topcut stattgefunden hat.', verbose_name='Datum *'),
        ),
        migrations.AlterField(
            model_name='topcut',
            name='plot',
            field=models.ForeignKey(help_text='Der Schlag, für den der Kopfschnitt durchgeführt wurde.', on_delete=django.db.models.deletion.CASCADE, related_name='topcuts', to='hempdata.plot', verbose_name='Schlag *'),
        ),
        migrations.AlterField(
            model_name='weedcontrolchemical',
            name='plot',
            field=models.ForeignKey(help_text='Der Schlag, auf dem die chemische Unkrautbekämpfung durchgeführt wurde.', on_delete=django.db.models.deletion.CASCADE, related_name='chemical_weed_controls', to='hempdata.plot', verbose_name='Schlag *'),
        ),
        migrations.AlterField(
            model_name='weedcontrolmechanic',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, help_text='Das Datum, an dem die Unkrautbekämpfung vorgenommen wurde.', verbose_name='Datum *'),
        ),
        migrations.AlterField(
            model_name='weedcontrolmechanic',
            name='plot',
            field=models.ForeignKey(help_text='Der Schlag, für den die mechanische Unkrautbekämpfung durchgeführt wurde.', on_delete=django.db.models.deletion.CASCADE, related_name='mechanic_weed_controls', to='hempdata.plot', verbose_name='Schlag *'),
        ),
    ]
