# Generated by Django 5.1.3 on 2025-01-07 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hempdata', '0031_alter_bailing_plot_alter_conditioning_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalData',
        ),
    ]
