# Generated by Django 5.1.3 on 2025-01-07 12:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hempdata', '0032_delete_historicaldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Eindeutige ID der historischen Daten.', primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_crop', models.CharField(help_text='Die erste Vorfrucht, die im Vorjahr auf diesem Schlag angebaut wurde.', max_length=255, verbose_name='Vorfrucht 1')),
                ('created_at', models.DateField(auto_now_add=True, help_text='Das Datum, an dem die historischen Daten erfasst wurden.', verbose_name='Erhebungszeitpunkt')),
                ('plot', models.ForeignKey(help_text='Das Feld (Plot), dem diese historischen Daten zugeordnet sind.', on_delete=django.db.models.deletion.CASCADE, related_name='historical_data', to='hempdata.plot', verbose_name='Schlag *')),
            ],
            options={
                'verbose_name': 'Historische Daten',
                'verbose_name_plural': 'Historische Daten',
                'constraints': [models.UniqueConstraint(fields=('plot',), name='unique_plot_historical_data')],
            },
        ),
    ]
