# Generated by Django 5.1.3 on 2025-01-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hempdata', '0033_historicaldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldata',
            name='created_at',
            field=models.DateField(help_text='Das Datum, an dem die historischen Daten erfasst wurden.', verbose_name='Erhebungszeitpunkt'),
        ),
    ]
