# Generated by Django 5.1.3 on 2025-01-07 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hempdata', '0036_historicaldata_sommerung_historicaldata_winterung_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaldata',
            name='season',
        ),
    ]
