# Generated by Django 5.1.3 on 2025-01-08 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hempdata', '0040_soilpreparation_additional_information_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soilpreparation',
            name='completed',
        ),
    ]
