# Generated by Django 5.1.3 on 2025-01-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hempdata', '0041_remove_soilpreparation_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soilpreparation',
            name='intensity',
            field=models.CharField(choices=[('flach', 'Flach'), ('mittel', 'Mittel'), ('tief', 'Tief')], help_text='Die Intensität der Bodenvorbereitung.', max_length=10, verbose_name='Intensität'),
        ),
        migrations.AlterField(
            model_name='soilpreparation',
            name='type',
            field=models.CharField(choices=[('grubbern', 'grubbern'), ('eggen', 'eggen'), ('pflügen', 'pflügen')], help_text='Die Art der durchgeführten Bodenvorbereitung.', max_length=10, verbose_name='Art der Durchführung'),
        ),
    ]
