# Generated by Django 5.1.3 on 2025-01-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hempdata', '0044_alter_historicaldata_previous_crop_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fertilization',
            name='completed',
        ),
        migrations.AddField(
            model_name='fertilization',
            name='dosage_form',
            field=models.CharField(blank=True, choices=[('?', '?')], max_length=50, null=True, verbose_name='Darreichungsform'),
        ),
        migrations.AlterField(
            model_name='fertilization',
            name='fertilizer',
            field=models.CharField(choices=[('Stickstoff', 'Stickstoff'), ('Phosphor', 'Phosphor'), ('Kalk', 'Kalk'), ('Kalium', 'Kalium'), ('Magnesium', 'Magnesium')], help_text='Der verwendete Dünger (z. B. NPK, Kalk).', max_length=50, verbose_name='Dünger'),
        ),
    ]
