# Generated by Django 5.1.3 on 2025-01-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hempdata', '0045_remove_fertilization_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeding',
            name='sorte',
            field=models.CharField(blank=True, choices=[('Ostara 9', 'Ostara 9'), ('Nashinoïde 15', 'Nashinoïde 15'), ('Mona 16', 'Mona 16'), ('Djumbo 20', 'Djumbo 20'), ('Muka 76', 'Muka 76'), ('Futura 83', 'Futura 83'), ('Santhica 27', 'Santhica 27'), ('Futura 75', 'Futura 75'), ('Fibror 79', 'Fibror 79'), ('Felina 32', 'Felina 32'), ('Fedora 17', 'Fedora 17'), ('Ferimon', 'Ferimon'), ('Earlina 08', 'Earlina 08'), ('USO 31', 'USO 31'), ('Dioïca 88', 'Dioïca 88')], max_length=255, null=True, verbose_name='Sorte'),
        ),
        migrations.AlterField(
            model_name='seeding',
            name='seedbed_width',
            field=models.IntegerField(default=12.5, verbose_name='Reihenabstand (cm)'),
        ),
        migrations.AlterField(
            model_name='seeding',
            name='thousand_grain_weight',
            field=models.FloatField(help_text='Das Gewicht von tausend Körnern der ausgesäten Kultur (in Gramm).', verbose_name='Tausendkorngewicht (g)'),
        ),
        migrations.AlterField(
            model_name='seeding',
            name='variety',
            field=models.CharField(choices=[('Hanf', 'Hanf'), ('Flachs', 'Flachs')], help_text='Kulturart (z.B. Hanf, Flachs).', max_length=255, verbose_name='Kulturart'),
        ),
    ]
