# Generated by Django 5.1.3 on 2025-01-09 08:53

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hempdata', '0047_alter_seeding_seedbed_width_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlotParts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Der Name des Teilschlags, um ihn eindeutig zu identifizieren.', max_length=255, verbose_name='Name des Teilschlags')),
                ('size', models.IntegerField(help_text='Die Größe des Teilschlags in Quadratmetern.', verbose_name='Größe des Teilschlags (m²)')),
                ('location', django.contrib.gis.db.models.fields.PolygonField(help_text='Polygongeometrie zur Darstellung der geographischen Lage des Teilschlags.', srid=4326, verbose_name='Geographische Lage')),
                ('created_at', models.DateField(auto_now_add=True, help_text='Datum, an dem der Teilschlags erfasst wurde.', verbose_name='Erhebungszeitpunkt')),
                ('plot', models.ForeignKey(help_text='Der Schlag, dem dieser Teilschlags zugeordnet ist.', on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='hempdata.plot', verbose_name='Zugehöriger Schlag')),
            ],
            options={
                'verbose_name': 'Standort - Teilschlag',
                'verbose_name_plural': 'Standort - Teilschläge',
            },
        ),
    ]
