# Generated by Django 5.1.3 on 2025-01-09 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hempdata', '0049_alter_harvest_options_remove_harvest_plot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conditioning',
            name='plot',
        ),
        migrations.AddField(
            model_name='conditioning',
            name='plotpart',
            field=models.ForeignKey(blank=True, help_text='Der Teilschlag, für den die Ernte vorgenommen wurde.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conditioning', to='hempdata.plotparts', verbose_name='Teilschlag *'),
        ),
    ]
