# Generated by Django 5.1.3 on 2025-01-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hempdata', '0050_remove_conditioning_plot_conditioning_plotpart'),
    ]

    operations = [
        migrations.AddField(
            model_name='bailing',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Anzahl Ballen'),
        ),
    ]
