# Generated by Django 5.1.3 on 2025-01-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hempdata', '0051_bailing_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bailing',
            name='procedure',
            field=models.CharField(blank=True, choices=[('Rollen', 'Rollen'), ('Pressen', 'Pressen')], help_text='Die angewandte Prozedur zum Ballieren.', max_length=20, verbose_name='Prozedur'),
        ),
    ]
