# Generated by Django 5.1.3 on 2025-01-09 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hempdata', '0052_bailing_procedure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bailing',
            name='plot',
        ),
        migrations.AddField(
            model_name='bailing',
            name='plotpart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bailings', to='hempdata.plotparts', verbose_name='Teilschlag *'),
        ),
        migrations.AlterField(
            model_name='bailing',
            name='weight',
            field=models.IntegerField(blank=True, help_text='Stichprobenartiges Gewicht.', verbose_name='Gewicht'),
        ),
    ]
