# Generated by Django 5.1.3 on 2025-01-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hempdata', '0053_remove_bailing_plot_bailing_plotpart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weedcontrolmechanic',
            name='procedure_text',
            field=models.TextField(blank=True, null=True, verbose_name='Weitere Erläuterungen zum Prozess'),
        ),
    ]
