# Generated by Django 5.1.3 on 2025-01-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hempdata', '0054_weedcontrolmechanic_procedure_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantcharacteristicsbase',
            old_name='stem_thickness_one',
            new_name='stem_thickness',
        ),
        migrations.RemoveField(
            model_name='plantcharacteristicsbase',
            name='stem_thickness_two',
        ),
        migrations.AlterField(
            model_name='weedcontrolchemical',
            name='amount',
            field=models.IntegerField(help_text='Die ausgebrachte Menge der chemischen Substanz.', verbose_name='Menge (l/ha)'),
        ),
        migrations.AlterField(
            model_name='weedcontrolchemical',
            name='substance',
            field=models.CharField(help_text='Die verwendete chemische Substanz zur Unkrautbekämpfung.', max_length=255, verbose_name='Handelsname'),
        ),
    ]
