# Generated by Django 5.1.3 on 2025-01-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hempdata', '0055_rename_stem_thickness_one_plantcharacteristicsbase_stem_thickness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantcharacteristicsbase',
            name='growth_form',
            field=models.IntegerField(blank=True, choices=[(10, '10%'), (20, '20%'), (30, '30%'), (40, '40%'), (50, '50%'), (60, '60%'), (70, '70%'), (80, '80%'), (90, '90%'), (100, '100%')], null=True, verbose_name='Wuchsform (ungefährer %-Anteil gerade)'),
        ),
        migrations.AlterField(
            model_name='plantcharacteristicsbase',
            name='shoots_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anzahl Doppeltriebe'),
        ),
        migrations.AlterField(
            model_name='plantcharacteristicsbase',
            name='stem_thickness',
            field=models.IntegerField(verbose_name='Stängeldicke'),
        ),
    ]
