# Generated by Django 5.1.3 on 2025-01-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hempdata', '0056_alter_plantcharacteristicsbase_growth_form_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soilsample',
            name='soil_compaction',
        ),
        migrations.AlterField(
            model_name='plantcharacteristicsbase',
            name='growth_form',
            field=models.IntegerField(blank=True, choices=[(10, '10%'), (20, '20%'), (30, '30%'), (40, '40%'), (50, '50%'), (60, '60%'), (70, '70%'), (80, '80%'), (90, '90%'), (100, '100%')], null=True, verbose_name='Wuchsform'),
        ),
        migrations.AlterField(
            model_name='plantcharacteristicsbase',
            name='plant_density',
            field=models.IntegerField(verbose_name='Pflanzendichte'),
        ),
    ]
