# Generated by Django 5.1.3 on 2025-01-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hempdata', '0057_remove_soilsample_soil_compaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soilsample',
            name='cn_ratio',
            field=models.CharField(blank=True, help_text='Verhältnis von Kohlenstoff zu Stickstoff', max_length=255, null=True, verbose_name='C/N Verhältnis'),
        ),
    ]
