# Generated by Django 5.1.3 on 2025-01-09 11:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hempdata', '0058_alter_soilsample_cn_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soilsample',
            name='sampling_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Datum der Bodenprobenahme', verbose_name='Probenahmedatum *'),
        ),
    ]
