# Generated by Django 5.1.4 on 2025-01-16 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hempdata', '0059_alter_soilsample_sampling_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantVariety',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Hanf', 'Hanf'), ('Flachs', 'Flachs')], max_length=10)),
            ],
            options={
                'verbose_name': 'Sortenliste',
                'verbose_name_plural': 'Sortenliste',
            },
        ),
        migrations.CreateModel(
            name='PreviousCrop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Vorfrüchte',
                'verbose_name_plural': 'Vorfrüchte',
            },
        ),
        migrations.AlterModelOptions(
            name='soilsample',
            options={'verbose_name': 'Verlaufsanalytik - Manuell - Bodenproben', 'verbose_name_plural': 'Verlaufsanalytik - Manuell - Bodenproben'},
        ),
        migrations.AlterField(
            model_name='seeding',
            name='sorte',
            field=models.ForeignKey(default='Avian', on_delete=django.db.models.deletion.CASCADE, related_name='seeding', to='hempdata.plantvariety', verbose_name='Sorte'),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='previous_crop',
            field=models.ForeignKey(default='Hanf', help_text='Welche Vorfrucht wurde auf dem Schlag bereits angebaut?', on_delete=django.db.models.deletion.CASCADE, related_name='historical_data', to='hempdata.previouscrop', verbose_name='Vorfrucht'),
        ),
    ]
