# Generated by Django 5.1.4 on 2025-01-16 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hempdata', '0060_plantvariety_previouscrop_alter_soilsample_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaldata',
            name='previous_crops',
            field=models.ForeignKey(help_text='Welche Vorfrucht wurde auf dem Schlag bereits angebaut?', on_delete=django.db.models.deletion.CASCADE, related_name='historical_data', to='hempdata.previouscrop', verbose_name='Vorfrucht'),
        ),
    ]
